<?php

/**
 * Created by PhpStorm.
 * User: lo
 * Date: 11/09/18
 * Time: 21:06
 */
class ManutArisque extends Manutentionnaire implements ARisque
{
    public function  calculerSalaire()
    {
        return parent::calculerSalaire() + self::PRIME; // TODO: Change the autogenerated stub
    }

}