<?php

class Enseignant extends Personnel
{
    private $section;
    
    public function __construct($nom, $annee, $labo, $salaire, $section)
    {
        parent::__construct($nom, $annee, $labo, $salaire);
        $this->section = $section;
    }


    public function getSection()
    {
        return $this->section;
    }

    public function afficher()
    {
        echo " Enseignant :";
        parent::afficher(); // TODO: Change the autogenerated stub
        echo " Section : ".$this->section;
    }
}