<?php

class Etudiant extends EPFlien
{
    private $section;

    public function __construct($nom, $annee, $section)
    {
        parent::__construct($nom, $annee);
        $this->section = $section;
    }

    public function afficher()
    {
        echo " Etudiant <br>";
        parent::afficher(); // TODO: Change the autogenerated stub
        echo " Section : ".$this->section;
    }

    public function getSection()
    {
        return $this->section;
    }

    public function estEtudiant():bool
    {
        return true;
    }
}