<?php

class EtudiantRegulier extends Etudiant
{
    private $moyenne;
    
    public function __construct($nom, $annee, $section, $moyenne)
    {
        parent::__construct($nom, $annee, $section);
        $this->moyenne = $moyenne;
    }

    public function afficher()
    {
        echo " Etudiant regulier <br>";
        parent::afficher(); // TODO: Change the autogenerated stub
        echo " Moyenne : ".$this->moyenne;
    }

}