<?php

class Personnel extends EPFlien
{
    private $labo;
    private $salaire;

    public function __construct($nom, $annee, $labo, $salaire)
    {
        parent::__construct($nom, $annee);
        $this->salaire = $salaire;
        $this->labo = $labo;
    }

    public function afficher()
    {
        parent::afficher(); // TODO: Change the autogenerated stub
        echo " Laboratoire :".$this->labo;
        echo "Saliere :".$this->salaire;
    }

    public function getLabo()
    {
        return $this->labo;
    }

    public function getSalaire()
    {
        return $this->salaire;
    }
}