<?php

class Colis extends Courrier
{
    protected $volume;

    public function __construct($poids, $express, $adresse, $volume)
    {
        parent::__construct($poids, $express, $adresse);
        $this->volume = $volume;
    }

    public function affranchirNormal()
    {
        return 0.25 * $this->volume + $this->poids/1000;
    }

    public function valide()
    {
        return parent::valide() && $this->volume<=50; // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        $s = " Colis ";
       $s.= parent::__toString(); // TODO: Change the autogenerated stub
        $s.= " Volume : ".$this->volume;

        return $s;
    }
}