<?php

class Publicite extends Courrier
{
    public function __toString()
    {
        $s = " Publicite ";
        $s.= parent::__toString(); // TODO: Change the autogenerated stub

        return $s;
    }
}